// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Crypto is an autogenerated mock type for the Crypto type
type Crypto struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: encrypted, iv
func (_m *Crypto) Decrypt(encrypted string, iv string) string {
	ret := _m.Called(encrypted, iv)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(encrypted, iv)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Encrypt provides a mock function with given fields: plaintext, iv
func (_m *Crypto) Encrypt(plaintext string, iv string) string {
	ret := _m.Called(plaintext, iv)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(plaintext, iv)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
