// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/dgrijalva/jwt-go"

	mock "github.com/stretchr/testify/mock"
)

// JSONWebToken is an autogenerated mock type for the JSONWebToken type
type JSONWebToken struct {
	mock.Mock
}

// Parse provides a mock function with given fields: ctx, tokenString, claims
func (_m *JSONWebToken) Parse(ctx context.Context, tokenString string, claims jwt.Claims) error {
	ret := _m.Called(ctx, tokenString, claims)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, jwt.Claims) error); ok {
		r0 = rf(ctx, tokenString, claims)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sign provides a mock function with given fields: ctx, claims
func (_m *JSONWebToken) Sign(ctx context.Context, claims jwt.Claims) (string, error) {
	ret := _m.Called(ctx, claims)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) string); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, jwt.Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
